version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/lwb/my-blog-docker-build/nginx/html:/usr/share/nginx/html
      - /home/lwb/my-blog-docker-build/nginx/nginx.conf:/etc/nginx/conf/conf.d/nginx.conf
    privileged: true
  mysql:
    image: mysql:8.0.29
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=lwb090512
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  my-blog:
    image: my-blog:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
